### ISSUE TITLE
Error creating subnet: InvalidParameterValue: Value (us-west-1a) for parameter availabilityZone is invalid.

### ISSUE THREAD

**Issue by cryptonymco** [Coalfire-Research/npk#10]
I receive the following error. It appears to be AWS account related in that I can not create a subnet in us-west-1a. Is there a way to exclude this availability zone?

Error: Error applying plan:

1 error(s) occurred:

* aws_subnet.us-west-1a: 1 error(s) occurred:

* aws_subnet.us-west-1a: Error creating subnet: InvalidParameterValue: Value (us-west-1a) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-west-1b, us-west-1c.
	status code: 400, request id: omitted

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by c6fc** [comment]
Can you please post the result of the following two commands from the `npk/terraform/` folder

`cat generated-settings.jsonnet | jq '.regions["us-west-1"]'`

`aws --profile $(jq -r '.awsProfile' npk-settings.json) ec2 --region us-west-1 describe-availability-zones | jq '{"us-west-1": [.AvailabilityZones[] | select(.State=="available") | .ZoneName]}'`

**Comment by cryptonymco** [comment]
$ cat generated-settings.jsonnet | jq '.regions["us-west-1"]'
[
  "us-west-1a",
  "us-west-1c"
]

$ aws --profile $(jq -r '.awsProfile' npk-settings.json) ec2 --region us-west-1 describe-availability-zones | jq '{"us-west-1": [.AvailabilityZones[] | select(.State=="available") | .ZoneName]}'
{
  "us-west-1": [
    "us-west-1a",
    "us-west-1c"
  ]
}


Thanks!

**Comment by c6fc** [comment]
That's odd. `aws ec2 describe-availability-zones` shouldn't return us-west-1a if it's not available.

For now, try this as a workaround:

1. Change `us-west-1a` to `us-west-1b` in the `terraform/generated-settings.json` file
2. Comment out line 69 of deploy.sh, which looks like `jq ... > generated-settings.json`
3. Run the `deploy.sh` script from the `npk/terraform` directory

**Comment by c6fc** [comment]
@cryptonymco any luck with this workaround?
