### ISSUE TITLE
x-amz-meta-lines and x-amz-meta-size missing from most wordlists

### ISSUE THREAD

**Issue by kataze** [Coalfire-Research/npk#101]
![image](https://user-images.githubusercontent.com/1631158/85460217-dd6e5880-b557-11ea-8071-5af511d58c8a.png)

Some of the built in word-lists seem to be missing metadata headers that are used in calculation of the completion date, which are needed to do the coverage calculations.

**Comment by awhitehatter** [comment]
Thanks for catching this, added these in tonight.
