### ISSUE TITLE
Spot Instance terminated due to user-initiated termination. [instance-terminated-by-user]

### ISSUE THREAD

**Issue by mother2110** [Coalfire-Research/npk#103]
I never terminated this job. Was it just too much to handle? I was running a brute force attack.

**Comment by thalesredteam** [comment]
Any logging output?

**Comment by mother2110** [comment]
Ya, sorry I forgot to update this. I set to brute force for 24 hours and it AWS terminated due to resources.

**Comment by mother2110** [comment]
terminated due to resources
