### ISSUE TITLE
Multiple GPU instances

### ISSUE THREAD

**Issue by thalesredteam** [Coalfire-Research/npk#104]
So by default, wether you deploy the Master or V2 branch you are able to only select 1 GPU intances.
Why is this? Shouldn't we be able to launch multiple GPU cracking boxes?

**Comment by almart** [comment]
From the NPK wiki:

> By default, AWS is very restrictive about the number of GPU-powered instances you can run on new accounts. In order to use more than one instance for your campaigns, you'll need to request an increase to your limits. Click the following link to submit the increase request: https://console.aws.amazon.com/support/cases#/create?issueType=service-limit-increase&limitType=ec2-instances

https://github.com/Coalfire-Research/npk/wiki/Detailed-Usage-Instructions

I am in process of deploying NPK and just made the request to AWS. Have you already done this step?

**Comment by c6fc** [comment]
@thalesredteam you can only select one instance *type*. The instance count slider at the bottom of the New Campaign page let's you specify how many of them to create.
