### ISSUE TITLE
Error invalid or unknown key: unused_account_validity_days

### ISSUE THREAD

**Issue by NickstaDB** [Coalfire-Research/npk#106]
Just did a fresh git clone and hit the following error while attempting to run this:

```
Error: aws_cognito_user_pool.npk: admin_create_user_config.0: invalid or unknown key: unused_account_validity_days
```

After some digging I managed to resolve this by modifying https://github.com/Coalfire-Research/npk/blob/master/terraform/jsonnet/provider.libsonnet and adding the following to each `aws` block:

```
version: "~> 2.39.0"
```

Not sure which version of the AWS provider you lot used (presumably the latest at the time of dev) but it might save a few headaches if you fix the version as above.

**Comment by pasyn** [comment]
What version of terraform are you using? Try using version 0.11 as stated in the installation instructions. Previous versions of terraform can be found here: [https://releases.hashicorp.com/terraform/](https://releases.hashicorp.com/terraform/)

**Comment by blark** [comment]
I also missed the version requirement on Terraform. Just a suggestion (which I can submit a pull for if you like) maybe add a version check to deploy.sh to avoid this? Thanks!

**Comment by c6fc** [comment]
I added a check to deploy.sh to verify the terraform version, and also updated the terraform code to remove the deprecated attribute. Both changes are in the v2 branch currently.
