### ISSUE TITLE
Suggest Spot Instance quota increase in docs for new accounts?

### ISSUE THREAD

**Issue by bigpick** [Coalfire-Research/npk#107]
# Info
If creating a new AWS account/a not-frequently used account, the default EC2 spot instance quota is 1, so any campaign that is started will have any other than the first VM fail due to quota issues; example from the AWS console on a fresh account's first campaign run:

```
sfr-4d4d2648-1d2f-4c54-9939-221d8855666d | fleet | p2.xlarge | active | 1 of 2 | pending_fulfillment | request | 17 minutes ago
```

And inspecting that, the second instance will never come up because:

```
launchSpecTemporarilyBlacklisted
--
Repeated errors have occurred processing the launch specification "p2.xlarge, ami-09144ebbb8d7191e3, Linux/UNIX, us-east-1e while launching spot instance". It will not be retried for at least 13 minutes. Error message: Max spot instance count exceeded (Service: AmazonEC2; Status Code: 400; Error Code: MaxSpotInstanceCountExceeded; Proxy: null)
--
```

Might it be worthwhile to mention in the main README document that it is necesarry to do so for a fresh account, and [provide the link for requesting a limit increase (particularly for the p instances](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html).

... or at least specify that 
> [By default, there is an account limit of 20 Spot Instances per AWS Region ... and that Spot Instance limits are dynamic. When your account is new, your limit might be lower than 20 to start, but then increase over time ... If you submit a Spot Instance request and you receive the error Max Spot Instance count exceeded, you can go to the AWS Support Center and request a limit increase. ](https://docs.aws.amazon.com/whitepapers/latest/cost-optimization-leveraging-ec2-spot-instances/spot-request-limits.html)

**Comment by bigpick** [comment]
Actually... there's already #104 that kind of covers this. So... maybe a link or mention to the Wiki page, as that more or less has exactly what was posted above? https://github.com/Coalfire-Research/npk/wiki/Detailed-Usage-Instructions

**Comment by c6fc** [comment]
I've added a check to the deploy.sh in v2 which shows the current limit and fatally errors if it's too low.
