### ISSUE TITLE
Experiencing weird errors

### ISSUE THREAD

**Issue by hgondal** [Coalfire-Research/npk#109]
root@kali:/opt/npk/terraform# ./deploy.sh 
[*] Preparing to deploy NPK.
[*] Getting availabilityzones from AWS
[*] - us-east-1
[*] - us-east-2
[*] - us-west-1
[*] - us-west-2
[*] Checking service-linked roles for EC2 spot fleets

_**An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.**_
[*] Retrieving AWS credentials from profile
[*] Generating combined settings file
[*] Generating Terraform configurations
./acm.tf.json
./api_gateway.tf.json
./cloudfront.tf.json
./cloudwatch.tf.json
./cognito.tf.json
./cognito_iam_roles.tf.json
./data.tf.json
./dynamodb.tf.json
./dynamodb_settings.tf.json
./ec2_iam_roles.tf.json
./igw.tf.json
./keepers.tf.json
./keys.tf.json
./lambda_functions.tf.json
./lambda_iam_roles.tf.json
./null_resources.tf.json
./provider-aws.tf.json
./provider-other.tf.json
./route53.tf.json
./routetable.tf.json
./s3.tf.json
./sns.tf.json
./sqs.tf.json
./subnet.tf.json
./template-inject_api_handler.json
./templates.tf.json
./variables.tf.json
./vpc.tf.json
[*] Creating dynamic templates
**_./deploy.sh: line 86: terraform: command not found
./deploy.sh: line 87: terraform: command not found
./deploy.sh: line 88: terraform: command not found_**

**Comment by bigpick** [comment]
Do you have `terraform` installed?

```
which terraform
```
