### ISSUE TITLE
Create a UI notification indicating that hashrate estimates might not be trustworthy with salted/workfactor hashes.

### ISSUE THREAD

**Issue by bf-arhodes** [Coalfire-Research/npk#110]
Bcrypt $2*$ hashes can have vastly different hash rates based on the work factor that is used when computing the hash. This makes it impossible to properly size a campaign unless your hashes match the work factor that was used to come up with the estimates.

For example, I'm quoted 59,000h/s for $2*$, but I'm only getting 1,700k/s with $2a$10$.

**Comment by c6fc** [comment]
The hashrates are based on the output of `hashcat --benchmark` on each instance family, so salted hashes or algorithms with work-factors will never be accurate. If you're not sure what the performance will be like, start with a small instance and get a feel for the realistic hashrates based on the campaign settings you're using, then scale up.

**Comment by c6fc** [comment]
Fixed in 8de0be4
