### ISSUE TITLE
Invalid session state during DELETE https://NPK_URI/v1/userproxy/campaign/GUID request

### ISSUE THREAD

**Issue by nuschpl** [Coalfire-Research/npk#115]
Application launches XMLHTTPRequests to above endpoint and others despite som session token is no longer valid.
This causes in response:
/#/dashboard:1 Access to XMLHttpRequest at 'https://[BASE_URL]/v1/userproxy/campaign/0f317ba6-3b6d-4bb1-9b50-4c5deef13a75' from origin 'https://BASE_URL' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The proper behaviour would to periodically reach(once a few seconds or once a minut) userproxy via dedicated URI e.g like /session-state which would either prolong the session or fully logout the user so we won't be presented with no longer working interface

**Comment by c6fc** [comment]
Merged PR to pass-through the appropriate headers on the cloudfront distribution in both Master and v2 branches.
