### ISSUE TITLE
API Gateway https://https:// 

### ISSUE THREAD

**Issue by NotMedic** [Coalfire-Research/npk#116]
In [userdata.tpl](https://github.com/Coalfire-Research/npk/blob/fc45f32a76b92296939d7a23370dfe165f9c13d5/terraform/templates/userdata.tpl#L4), APIGATEWAY is defined using the full URI, including https://.  When this variable is used in hashcat_wrapper.js, this leads to a double protocol definition, causing API calls to fail since the host https://https is not defined. 

[apigateway definition](https://github.com/Coalfire-Research/npk/blob/fc45f32a76b92296939d7a23370dfe165f9c13d5/terraform-selfhost/compute-node/hashcat_wrapper.js#L14)

[apigateway usage with https:// prefixed](https://github.com/Coalfire-Research/npk/blob/fc45f32a76b92296939d7a23370dfe165f9c13d5/terraform-selfhost/compute-node/hashcat_wrapper.js#L45)

I would submit a pull request to modify userdata.tpl to strip the https:// off, but I'm unsure the downstream affects of that change or where else the variable is used. 

This should likely be fixed in the hashcat_wrapper.js in computer-node.zip hosted at 
s3://npk-dictionary-west-2-20181029005812750900000002/components-v2/compute-node.zip

**Comment by c6fc** [comment]
I believe this is fixed in c2232e5 - can you test when you get a chance?

**Comment by NotMedic** [comment]
_almost_.  :) You fixed it after a discord chat. To follow up, this should be to remove the redundant "/v1"

`"${aws_api_gateway_rest_api.npk.id}.execute-api." + settings.defaultRegion + ".amazonaws.com"`

**Comment by c6fc** [comment]
Done!
