### ISSUE TITLE
Role Creation Issue

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#118]
Hello, 

Please update deploy.sh to include npk profile from npk-settings file within commands below when initially executing. This will solve issues where localhost has multiple aws profiles configured. 

	aws iam create-service-linked-role --aws-service-name spot.amazonaws.com
	aws iam create-service-linked-role --aws-service-name spotfleet.amazonaws.com

**Comment by c6fc** [comment]
This is done via envvars to avoid putting in every command manually:

`PROFILE=$(jq -r '.awsProfile' npk-settings.json)
[...]
export AWS_PROFILE=$PROFILE`

Is it not creating on the correct profile despite this?

**Comment by bzekanovic** [comment]
For me it didn't create roles initially, but makes sense now that I read previous deploy commands. I'll do more testing to see if I can replicate this again.

**Comment by bzekanovic** [comment]
I believe this issue was on my side, but will re-open if I can replicate again. thx
