### ISSUE TITLE
Campaign - Info Improvement

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#121]
It would be nice if we could either add helpful text or rename some of the sections (see below) to make it more clear to the end users. 

Provisioning - I'm assuming this is how long it took for EC2 to provision?
First Crack - is this supposed to be when Hashcat started cracking first password or is this indicator that it cracked something?
Finished - does this mean it finished the campaign?

![image](https://user-images.githubusercontent.com/16389468/103002491-3e1d2480-44ec-11eb-875f-96158f38e236.png)

**Comment by c6fc** [comment]
Added tooltips in 0577069
