### ISSUE TITLE
Campaign - Weird UI 

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#122]
My campaign started, but seems like UI is supposed to show additional info (see screenshot), but its empty. What is NPK supposed to show in this section?

![image](https://user-images.githubusercontent.com/16389468/103002743-b1bf3180-44ec-11eb-8f53-5f3933317340.png)

**Comment by c6fc** [comment]
Fixed this and a few other visual oddities in Campaign Management view in 0577069
