### ISSUE TITLE
Settings HTML Bug

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#124]
Noticed that selecting icon below doesn't do anything. Not sure if you want to just remove it like when adding new user in User Administration settings. 

![image](https://user-images.githubusercontent.com/16389468/103146581-21aa0380-4709-11eb-9cd5-355c3b6c8336.png)

**Comment by c6fc** [comment]
Yeah, that's actually a pretty prolific issue for the modals. I'll deal with it before merging to master.

**Comment by c6fc** [comment]
Fixed in a2a885c
