### ISSUE TITLE
Password Reset Bug

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#128]
NPK throws error message below when user goes through password reset functionality, but new password is still set. 

![image](https://user-images.githubusercontent.com/16389468/103290887-c5184400-49a7-11eb-973e-509e0fa7c90b.png)

**Comment by c6fc** [comment]
Fixed this, along with some other bugs that were preventing the expected behavior. For example, it will now correctly auto-login when the password reset process is complete.
