### ISSUE TITLE
Admin User Management / Password Reset Flow Improvement

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#129]
I was testing new password reset functionality within NPK Admin User Mgm section and few things to consider. 

1. Admin selects password reset icon for end user. 
2. End user receives password reset code. 
3. End user navigates to NPK login, but there is no way for them to use that code since set new password view only shows up if user select "reset password" from login page on their own. 

I'm not sure if is possible to include password reset link to take end user to NPK page and show them view below when resetting their password from Admin User MGM page. 

![image](https://user-images.githubusercontent.com/16389468/103291302-a6667d00-49a8-11eb-8216-db5fda81d519.png)

**Comment by c6fc** [comment]
Workflow fixed in 8f8259b 

I'll consider adding a link as a part of UI cleanup.
