### ISSUE TITLE
Events Bug

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#131]
Events view user not visible when selecting node filter. 

![image](https://user-images.githubusercontent.com/16389468/103381469-1825f000-4aa9-11eb-938c-9f5a709d3f4e.png)

**Comment by ArchitektApx** [comment]
Are you behind on any commits? Works properly for me since https://github.com/Coalfire-Research/npk/commit/874b07403b5ce2296eb14d7117579723095cbc79

**Comment by c6fc** [comment]
This also only affects campaigns that were started *after* that commit is applied, since the user has to be injected into the campaign due to limitations in AWS Cognito.

**Comment by c6fc** [comment]
Also, this depends on using the updated hashcat_wrapper. If you're running selfhost, run a new `./deploy-selfhost.sh` followed by `./upload_npkcomponents.sh`, and the issue should be resolved on future campaigns.
