### ISSUE TITLE
deploy-selfhost.sh fails with error

### ISSUE THREAD

**Issue by drewbowski** [Coalfire-Research/npk#141]
When I run deploy-selfhost.sh it continually fails with the error

Error: null_resource.sync_npkcomponents: : invalid or unknown key: environment

[!] An error occurred while running terraform for selhost. Address the error and try again.

I have tried this on 2 separate machines with the same result. How do I fix this?

**Comment by c6fc** [comment]
What version of terraform were you using?

**Comment by c6fc** [comment]
Per a really old closed issue: https://github.com/Coalfire-Research/npk/issues/74#issuecomment-696777807

Using the latest version of terraform 11 solves this problem.
