### ISSUE TITLE
Ec2 403 error

### ISSUE THREAD

**Issue by yashar6909** [Coalfire-Research/npk#145]
Hi,

After a while and successfully installed and tested. 
I have this error "Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: d78deea1-26e4-4fb9-bb9f-be17614face5; Proxy: null)"

I destroyed and recreated, signed up for all the AMI, contacted support to increase, everything worked fine, until I needed it yesterday.

**Comment by original-galnar** [comment]
Same issue - (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: fb8ae326-3ef3-4400-aaf6-e30f016d42c2; Proxy: null)

My install has worked previously so I suspect something has changed on the AWS side. I am in the process of trying to run that down now.

**Comment by yashar6909** [comment]
If you find a solution, please share :) 
Thanks in advance.

**Comment by TangentPentest** [comment]
I had to add the following permissions to npk_lambda_api_handler_role:

iam:PassRole
ec2:RunInstances
ec2:CreateTags

For future reference I was able to identify these missing permissions by decoding the encoded error message:

aws --profile [$PROFILE] sts decode-authorization-message --encoded-message [$MESSAGE]

**Comment by original-galnar** [comment]
Thanks for this. I already had iam:PassRole but it had a constraint for one particular ARN. I had to update that constraint. Still not sure why this changed, but thanks for the help!

**Comment by yashar6909** [comment]
Solved for me.
For those not savy, you will find you need to add the permission in the lambda area of AWS. If the Devs could update this, it would be awesome!
Thanks again for this amazing projects

**Comment by c6fc** [comment]
Seems like the same thing as #148 

I'll get a fix added.

**Comment by c6fc** [comment]
Can someone please pull dev and give it a shot to see if the issue is addressed?

```git checkout dev
cd terraform
./deploy.sh```

there's no need to destroy before doing this. If it works, I'll push to master.
