### ISSUE TITLE
Question: Dictionary  Uploads

### ISSUE THREAD

**Issue by cyanide-hacker** [Coalfire-Research/npk#147]
I have some really great dictionaries for password cracking. Is there a way to upload these to the public repo so they can be used with NPK by default?

**Comment by c6fc** [comment]
Just drop a link to them. I'm always happy to add new dictionaries.

**Comment by cyanide-hacker** [comment]
The two files I use the most are at

 

https://download.weakpass.com/wordlists/1851/hashesorg2019.gz

https://download.weakpass.com/wordlists/1919/weakpass_2a.gz

 

If these can be added it would make this so much better for me.

 

Thanks
