### ISSUE TITLE
Error: Error requesting spot fleet: UnauthorizedOperation: You are not authorized to perform this operation.

### ISSUE THREAD

**Issue by JoepvA** [Coalfire-Research/npk#148]
When trying to start a campaign, this error shows up: _"Error: Error requesting spot fleet: UnauthorizedOperation: You are not authorized to perform this operation"_. How to fix this issue? Is it policy-related?

**Comment by JoepvA** [comment]
Found it within the issues, hard to find. 

Fix: 
1. Go to the "Lambda" service in the AWS console 
2. Click on proxy_api_handler
3. Click on configuration
4. In the permissions tab click on execution role link
5. Click on the policy -> edit policy
6. Within EC2, click on actions -> add "CreateTags" and "RunInstances"
7. Within IAM, change Resources to "All" instead of a specific one.

Thanks to the contributors on this [issue](https://github.com/Coalfire-Research/npk/issues/145) for the help!

**Comment by c6fc** [comment]
Gotta love it when AWS adds new permissions. I'll get this added.
