### ISSUE TITLE
Error when creating campaign with p3.x2large nodes

### ISSUE THREAD

**Issue by lbalart** [Coalfire-Research/npk#157]
Hello, 

When trying to launch a campaign using p3.2xlarge nodes, an error indicanting the number of nodes must be greater or equal than 1 appears, while I am selecting 30 nodes with a duration of 9h in order to crack my hashes:

![image](https://user-images.githubusercontent.com/87477402/125780139-de4e6cf6-e246-43b8-b826-aad7465e93dc.png)

The JSON object is created succesfully with the instanceCount value to 30:

![image](https://user-images.githubusercontent.com/87477402/125780328-63ebb10c-4aa2-4320-838a-23c50f58a165.png)

The POST request indicates a instanceCount value of 30 but the server response is a 400 error indicating the same error as above:

![image](https://user-images.githubusercontent.com/87477402/125780749-a613df35-ee27-43a1-b549-1111e34704cf.png)
![image](https://user-images.githubusercontent.com/87477402/125780854-c03af55e-f90e-435f-a84a-aea93c39a045.png)

**Comment by c6fc** [comment]
This repo isn't supported anymore - if you need support in a more timely manner, make sure to post issues in the new repo referenced by the readme.

NPK has a hard-coded upper limit of 6 instances per campaign, but the error message doesn't indicate this. Consider using fewer, larger, and longer-lasting instances to get below this threshold.
