### ISSUE TITLE
[feature request] run hashcat with --username so hashes with usernames prepended can be uploaded and cracked

### ISSUE THREAD

**Issue by thesle3p** [Coalfire-Research/npk#19]
I'm not sure why this isn't already supported but you can give hashcat a hashfile with username:hash in it if you provide hashcat the --username flag and can be submitted as a outfile with --outfile-format 3, can you add  support for this in NPK? It saves time from having to grep a potfile for a user's hash value.

**Comment by c6fc** [comment]
This was intentionally not included, since we don't want usernames uploaded with their hashes wherever we can avoid it.

I'm already planning to add an in-browser correlation utility to help with this, but for now you have to manually correlate your results.
