### ISSUE TITLE
hardcoded paths to home dir in terraform-selfhost

### ISSUE THREAD

**Issue by l0ss** [Coalfire-Research/npk#22]
terraform-selfhost/templates/upload_npkcomponents.sh.tpl
and 
terraform-selfhost/upload_npkcomponents.sh

both contain hardcoded paths to /home/brad/

which obviously cause issues.

**Comment by c6fc** [comment]
I've pushed a fix to upload_npkcomponents.sh.tpl.

upload_npkcomponents.sh is overwritten by terraform when you create your own buckets, so it's not necessary to change that.
