### ISSUE TITLE
Add ability to manually provide hash type

### ISSUE THREAD

**Issue by thesle3p** [Coalfire-Research/npk#25]
So for whatever reason the vBulletin hashcat modes are not showing up in the drop down menu when I try and create a campaign. are they not supported? Or if it's a bug would it be possible to manually provide a hashcat mode without using the dropdown?

**Comment by c6fc** [comment]
Heyo.

Both those hash modes were recently added by the hashcat project, and NPK currently runs on hashcat 5.0.0, which may not support those hash types. It's on the roadmap to upgrade and add the newer hash types, but it won't happen for another couple months.

If you need bleeding edge hash types, you can try specifying 5.1.0 in terraform-selfhost and adding the hashTypes to the JSON array in site-content/angular/services/pricingSvc.js, but I can't make any promises as to whether it'll work right off the bat.

For now though, hash types released after 5.0.0 aren't supported. Sorry about that.

**Comment by thesle3p** [comment]
Version 5.0.0 supports Vbulletin hashes, I am not sur e why you think it doesn't.....

**Comment by c6fc** [comment]
I'll add the ability to specify a number instead of select from the dropdown. I can't guarantee that it will work if you select a hash type not included in the dropdown, but if it does, then that should get you going again.

**Comment by justingoesfpv** [comment]
> Heyo.
> 
> Both those hash modes were recently added by the hashcat project, and NPK currently runs on hashcat 5.0.0, which may not support those hash types. It's on the roadmap to upgrade and add the newer hash types, but it won't happen for another couple months.
> 
> If you need bleeding edge hash types, you can try specifying 5.1.0 in terraform-selfhost and adding the hashTypes to the JSON array in site-content/angular/services/pricingSvc.js, but I can't make any promises as to whether it'll work right off the bat.
> 
> For now though, hash types released after 5.0.0 aren't supported. Sorry about that.

I can confirm simply modifying pricingSvc.js works, just issue the sync command after editing.

**Comment by c6fc** [comment]
Added an advanced view in v2 2608dbc where a hash type can be provided manually. This should speed up the selection process, though it may cause other UI issues if there aren't benchmarks associated with the custom hashtype you enter. This is (as named) an advanced feature, so please let me know if you encounter any other issues.
