### ISSUE TITLE
[feature request] Support uploading of Maskfiles 

### ISSUE THREAD

**Issue by thesle3p** [Coalfire-Research/npk#26]
Would it be possible to support the uploading of Maskfiles? It is often more efficient to use a set of  masks in a .hcmask file than to run masks serially.

**Comment by c6fc** [comment]
This would be a pretty substantial thing to add, but I'm not opposed to adding it to the roadmap if I understood the benefits a bit better. Is there some reason that this would be better than generating a custom rule file using the maskprocessor?

**Comment by c6fc** [comment]
I'm not seeing any benefit to maskfiles that can't be accommodated with rules generated with the maskprocessor. I'm going to close this. If there's a usecase that isn't covered here, feel free to post the details and re-open.
