### ISSUE TITLE
UnauthorizedOperation error when attempting to start a campaign.

### ISSUE THREAD

**Issue by c6fc** [Coalfire-Research/npk#29]
I encountered this for the first time last week, but thought it was limited to myself. I got an email from a colleague saying that this was affecting their implementation as well:

<img width="1342" alt="npk_errir" src="https://user-images.githubusercontent.com/143415/59405722-b425c480-8d68-11e9-9c98-2e3abaa73c34.png">

On closer inspection, this appears to be occurring because of a permissions change on AWS end, since adding a global allow on the IAM role for the Proxy API Handler resolves the issue. Track this down and fix it ASAP.

**Comment by c6fc** [comment]
Turns out AWS added a check for iam:PassRole when performing requestSpotFleet() which wasn't previously occurring (lol). Since the Lambda execution role for the Proxy API Handler didn't include permissions to pass the Spot Fleet Role, it was throwing an error.

By adding the explicit permission into the Proxy API Handler execution role, this error no longer occurs.

To push this change, do the following from your git repo directory:
`git pull
cd terraform
./deploy.sh`

Please let me know by responding to this thread if this does not fix your issue.

**Comment by swarleysez** [comment]
I was having the exact same issue and that seemed to fix it, thanks.
