### ISSUE TITLE
npm not found during initial deployment

### ISSUE THREAD

**Issue by audibleblink** [Coalfire-Research/npk#3]
Despite having `npm` installed and pulling latest master from today where npm was added to the dep checks, I'm getting the following errors.

```
Error: Error applying plan:

3 error(s) occurred:

* null_resource.npm_install_spot_monitor: Error running command 'cd /root/npk/terraform/lambda_functions/spot_monitor/ && npm install': exit status 127. Output: /bin/sh: 1: npm: not found
* null_resource.npm_install_status_reporter: Error running command 'cd /root/npk/terraform/lambda_functions/status_reporter/ && npm install': exit status 127. Output: /bin/sh: 1: npm: not found
* null_resource.npm_install_proxy_api_handler: Error running command 'cd /root/npk/terraform/lambda_functions/proxy_api_handler/ && npm install': exit status 127. Output: /bin/sh: 1: npm: not found
```

**Comment by c6fc** [comment]
It looks like you're running the deploy script as root. Does the root user have npm installed?

`sudo npm --version`

**Comment by audibleblink** [comment]
DO droplets "encourage" the `snap` installation of terraform when running `apt get`.
I installed via instructions from Hashicorp and all is well. I'll close but at least it's here for future searchers.
