### ISSUE TITLE
[request] list of all aws instances and resources used (report/log)

### ISSUE THREAD

**Issue by dogasantos** [Coalfire-Research/npk#30]
hey guys,
first of all, thanks for this amazing tool !

I was wondering, it will be possible to add a listing of all aws resources this tool creates during the deployment ? Even on failed terraform attempts. My notebook crashed during the first attempt, and I can see the related bucket there. So I'm not sure if there is still some residual aws resource being used from that broken setup.

Thanks guys!

**Comment by dogasantos** [comment]
ps: yeap, just bought a new laptop. That part is already fixed. :)

**Comment by c6fc** [comment]
It's not possible to recover the Terraform state from an aborted run - that's a limitation of Terraform.

If you followed the advice in the wiki and used a dedicated account, you can easily use the tag manager to find resources created in all US regions. Almost all resources created by Terraform for NPK have a tag of 'Environment': 'NPK', which could help you track things down.
