### ISSUE TITLE
New campaigns stuck in 'Starting'

### ISSUE THREAD

**Issue by c6fc** [Coalfire-Research/npk#33]
NVidia recently released a new AMI which requires a different subscription in order to use. If your campaigns are stuck in 'starting', check the spot fleet history to see what the error is; you might see something like this:

![Selection_115](https://user-images.githubusercontent.com/143415/60361937-d2143b80-999c-11e9-9d75-3e247fbc28ee.png)

If you follow the URL to the new subscription, you can subscribe, and your campaigns will no longer freeze.

I'll leave this issue open until I resolve it by removing the dependency on NVidia AMIs.

**Comment by c6fc** [comment]
Btw, the current subscription link is https://aws.amazon.com/marketplace/pp?sku=5rwcw3y2wbhixiw6qoi1gwdxt

**Comment by c6fc** [comment]
This seems pretty rare now, so I'm moving it to 'help wanted' and leaving it pinned. If folks encounter similar issues, post them here.

**Comment by 0x42424242** [comment]
> 
> 
> Btw, the current subscription link is https://aws.amazon.com/marketplace/pp?sku=5rwcw3y2wbhixiw6qoi1gwdxt

Thanks for this :) I know it's updated in the primary README, but you may want to update the link in this location as well - https://github.com/Coalfire-Research/npk/wiki/Detailed-Usage-Instructions#subscribe-to-nvidia-amis

Confused me the first time I saw that the link there had expired. 

Thanks for this awesome tool btw.

**Comment by c6fc** [comment]
Campaign management now exposes the SpotFleetRequestHistory for each campaign, along with the SpotInstanceRequest status for each spot instance created as part of the fleet. Collectively this means it's no longer necessary to inspect failures from inside the AWS console.

I'm leaving this open to address the nVidia link update in the documentation, but otherwise this might finally be good to close.

**Comment by ArchitektApx** [comment]
Link for the new Amazon Linux 2 AMI with NVIDIA TESLA GPU Driver wich is used since https://github.com/Coalfire-Research/npk/commit/b28a8c8219b206b9acb8b12e09dfadef8c288cb4:
https://aws.amazon.com/marketplace/pp/B07S5G9S1Z
