### ISSUE TITLE
Your fav methodology for cracking with NPK?

### ISSUE THREAD

**Issue by braimee** [Coalfire-Research/npk#34]
Sorry, this is not an issue per se but more of a curiosity that I think others would be interested in:

What's your fav methodology for using NPK to crack hashes - for example the NTLMv2s captured with something like Responder?

Thanks,
Brian

**Comment by c6fc** [comment]
The issues section isn't an ideal place to seek community feedback. Hashes.org has a very active Discord channel where you might find what you're looking for.
