### ISSUE TITLE
Error parsing response JSON

### ISSUE THREAD

**Issue by c6fc** [Coalfire-Research/npk#36]
If you are getting the message 'Error parsing response JSON' when submitting or attempting to start a campaign, follow the instructions below for help getting it fixed.

This happens because CloudFront and Lambda both handle requests differently for different geographic regions, and sometimes it doesn't include a piece that the API expects to see. 

For help troubleshooting, please gather the following information and send it to me via a direct message. The contents of the error and request can contain sensitive information unique to your deployment, so please don't post them publicly.

- [ ] Please use the web developer panel in your browser to show the request and response that caused the error. Request Headers and Response Headers are especially useful. A screenshot is ideal.
- [ ] Log into your AWS Account, navigate to the CloudWatch service, and inspect the logs for the 'proxy_api_handler' log group (this should appear in Oregon). The logs will look similar to this:

![Selection_114](https://user-images.githubusercontent.com/143415/60362505-54512f80-999e-11e9-8ff1-9ded82a7dc26.png)

- [ ] Locate the error, along with the closest 'Received event' log entry above it. Copy the contents of both, and include them in your message to me.

Once I've received the message, I'll work on troubleshooting the issue and will issue a fix. Thanks for using NPK!

**Comment by cyrinux** [comment]
Ok thanks @c6fc, will check this evening.

**Comment by cyrinux** [comment]
@c6fc is it normal is see nothing in cloudwatch? I must config this manually first? Sorry i'm newby on AWS services. Thanks for help.

**Comment by c6fc** [comment]
@cyrinux The cloudwatch logs will populate automatically once NPK is deployed. Here are a few things you can verify:

1. Make sure you aren't getting any errors from Terraform when you run the deploy. Try running `terraform apply` from the `npk/terraform/` directory.
2. When you're accessing the AWS Console, make sure you're in the us-west-2 (Oregon) region. This is where the Cloudwatch logs would appear for proxy_api_handler.

Out of curiosity, are you attempting to use NPK from outside the US? The other affected user is trying to execute from France, and I'm wondering if it could be an issue with AWS trying to grographically balance the executions, and it failing outside the US as a result.

**Comment by cyrinux** [comment]
@c6fc as see together is private, yes i was the case. But the main problem is cors settings are bad between the gateway and services in back. With disabling cors temporary this cors well, after fixing the bad permissions one my lambda files :)

**Comment by c6fc** [comment]
As you and I discovered, a strict umask on the NPK folder will prevent NPM from pulling package dependencies. To fix this, make sure that the user running the deploy.sh script has write access to the NPK folder:

```sh
cd npk/terraform/
umask 022
chmod -R o+rX .
./deploy.sh
```

NPK configures CORS on S3 and the API Gateway to prevent access-control-allow-origin issues. I'm not sure why you'd still be getting CORS errors, but I'm glad you have a workaround.

**Comment by tratteur** [comment]
Hi there. I'm no longer getting this error. I destroyed the environment, did a new git pull and then set it all up again. No more error but the job is stuck in 'STARTING' which might be related to the other issue here although I've accepted/subscribed to the new AMI.

**Comment by c6fc** [comment]
@tratteur can you follow the instructions in #33 to get the spot fleet history, and post it in that other issue?

Thanks in advance.

**Comment by reubenparr** [comment]
This error was resolved for me by using a VPN to the US (I am, Australia based).

I was also unable to get through to the cloudfront link as this had geo-restrictions, VPN cured both.

**Comment by c6fc** [comment]
I believe this has been resolved by the CORS changes. If anyone else encounters similar behavior, please open a new issue.
