### ISSUE TITLE
Factor salted hashes into campaign estimates

### ISSUE THREAD

**Issue by bytecod3r** [Coalfire-Research/npk#40]
The estimated time in the *-output.log file is 18 hours while the GUI was showing 1 hour.
![image](https://user-images.githubusercontent.com/8350933/60764994-c4119980-a0c5-11e9-9dcc-144873ba2b10.png)

![image](https://user-images.githubusercontent.com/8350933/60764968-962c5500-a0c5-11e9-836a-b2afa3e0def4.png)

Anyway I can fix it?

**Comment by c6fc** [comment]
Were you using a salted hash type (NetNTLMv2, bcrypt) with multiple hashes? The UI estimation doesn't account for multiple hashes with salted hash types, so you'll have to multiply the estimate by the number of hashes you have in your hash file.

**Comment by bytecod3r** [comment]
I was using a list of krb5-tgs hashes. TGS is not salted right? I'm not sure.

**Comment by c6fc** [comment]
I'm going to close this since #110 supercedes it.
