### ISSUE TITLE
Add ability to manually provide mask

### ISSUE THREAD

**Issue by rd6r4gdk24w729h5bdaz** [Coalfire-Research/npk#43]
Hi,
Thanks for your work on this product.
I would like to crack a hash using the "?H" mask wich is part of hashcat built-in charsets.
Unfortunately, the new campaign page only allow "?l?u?d?s?a?b" masks.
Do you think you could add "?H" and "?h" masks?
Or maybe add a text field so we can manually provide the mask?
Could you tell me wich file I must edit to bypass this limitation for now? Maybe I can just change the "?b" button to send a "?H" to hashcat as a temporary workaround...
Thanks.

**Comment by c6fc** [comment]
I'll add this to the list of features for the next version.

**Comment by rd6r4gdk24w729h5bdaz** [comment]
Thanks for the tip and the feature inclusion.

**Comment by c6fc** [comment]
Added in 874b074 along with custom parameter support.
