### ISSUE TITLE
2019-08-14T15:41:08+0000 : 2019-08-14T15:41:08+0000 : Spot Instance terminated due to user-initiated termination. [instance-terminated-by-user]

### ISSUE THREAD

**Issue by mother2110** [Coalfire-Research/npk#45]
When I launch a job, it runs for a few but then cancels with....

2019-08-14T15:41:08+0000 : 2019-08-14T15:41:08+0000 : Spot Instance terminated due to user-initiated termination. [instance-terminated-by-user]

8/14/2019, 8:57:48 AM	fleetRequestChange	cancelled		
8/14/2019, 8:51:42 AM	fleetRequestChange	cancelled_terminating		
8/14/2019, 8:42:53 AM	instanceChange	terminated	{"instanceType":"p3.2xlarge","image":"ami-07a1d900a353e49dd","productDescription":"Linux/UNIX","availabilityZone":"us-west-2c

**Comment by reubenparr** [comment]
I also get something similar:

![Screen Shot 2019-08-18 at 2 06 47 pm](https://user-images.githubusercontent.com/54226390/63219972-765a7780-c1c1-11e9-9a65-552b95863af2.png)

**Comment by mother2110** [comment]
I guess Coalfire doesn't monitor the Github page.

**Comment by c6fc** [comment]
Does the dashboard show a status update?
Do the instance logs show an error?

That looks like a successfully completed campaign to me. NPK will shut down the nodes when it's done.
