### ISSUE TITLE
NPK Password Reset Not Working

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#47]
Trying to reset password with NPK UI throws error message after user submits the password change with their new password / security token.

**Comment by c6fc** [comment]
Make sure you're using a new password that's at least 12 characters long, and sufficiently complex.

**Comment by bzekanovic** [comment]
Looks like password does get changed, but NPK UI still throws empty {} error message.

**Comment by bzekanovic** [comment]
@c6fc can you reproduce this on your side?

**Comment by c6fc** [comment]
@bzekanovic I'm not able to reproduce this, no. Can you share the contents of your npk-settings.json in a DM with the number and email removed?

**Comment by bzekanovic** [comment]
@c6fc  
See my sanitized config below. 

{
  "campaign_data_ttl": 604800,
  "campaign_max_price": 50,
  "georestrictions": ["US", "CA", "GB", "DE"],
  "useCustomDNS": true,
  "route53Zone": "<MYROUTE53ZONE>",
  "dnsNames": {
    "www": [
      "npk.<MY CUSTOM DOMAIN>"
    ],
    "api": [
      "api.npk.<MY CUSTOM DOMAIN>"
    ]
  },
  "awsProfile": "default",
  "criticalEventsSMS": "+<MY PHONE NUMBER>",
  "adminEmail": "<ADMIN EMAIL ADDRESS>"
}

Also, noticed that your documentation https://github.com/Coalfire-Research/npk/wiki/Creating-additional-users states to uncheck "Mark email as Verified" checkbox when creating new users. Un-checking this box disables the password reset option in NPK completely.

**Comment by c6fc** [comment]
I've added a user management console in 1223b9f which removes the need to directly interact with Cognito.
