### ISSUE TITLE
Events and Settings 

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#48]
Do you have any plans on deploying events and user settings within near future?

**Comment by c6fc** [comment]
Development of v2 is underway, which will enable these features.

**Comment by c6fc** [comment]
Setttings was added in e275476

Events is on the docket for tomorrow and Thursday.

**Comment by c6fc** [comment]
Events was fully integrated in 874b074 - it still needs some prettification, but it's there.
