### ISSUE TITLE
Campaign status "starting" does not change

### ISSUE THREAD

**Issue by Baesm** [Coalfire-Research/npk#5]
After configuring a campaign, the campaign is shown in the dashboard, but it does not start just stating "starting". This state does not change. Tried multiple reinstalls and configuring AWS, still no result. 

<img width="1280" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54855862-497c6400-4cf8-11e9-8409-6e84f8c80d74.png">

- edit - 
furthermore, in the "manage campaigns" tab it does state 

<img width="497" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54856383-8ea19580-4cfa-11e9-99b7-8d89f7b13d77.png">

how can I debug this error? Seems like an AWS thing.  

- edit - 
this is what I could get from the watchcloud logs. I am not experienced with AWS apart from using it for Alexa Skill programming. 

<img width="680" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54856620-b1807980-4cfb-11e9-9da8-44b21df1d125.png">

**Comment by c6fc** [comment]
Hi Baesm,

There are a few things you can check. The first is to see whether the EC2 spot requests are being fulfilled. Usually this would update after about 3 minutes, but if you're not seeing them, it could mean that the spot requests are failing. After starting a campaign, go to the EC2 service in the AWS console and click 'Spot Requests'. You should see one active spot request. If you click it, it will tell you a status in the bottom pane. What is the status? If it says fulfilled, try below.

The other possibility is that the Lambda function didn't upload properly, which most likely means you don't have NPM installed when doing the deploy. You can open Lambda in us-west-2, open the 'spot_monitor' lambda function, click 'Monitoring', and view the logs in CloudWatch. If it shows errors about not finding 'main.js', it means you don't have NPM installed properly. Install NPM, and run the deploy script again.

Let me know if either of these help!

**Comment by c6fc** [comment]
Also, I pushed an update this morning to make NPM failures more apparent. Before running the deploy script again, do a 'git pull'.

**Comment by swarleysez** [comment]
I'm having the same issue as the OP. The spot requests are not being populated. NPM was installed when I pushed out my deployment.

How can I debug the spot request failures?

**Comment by c6fc** [comment]
Follow the instructions above to view the spot fleet requests in the EC2 console. If you don't see any, try switching between the four regions until you find it. You can view the status of the fleet request itself by clicking it, and if it created any spot instances you can view their statuses by expanding the fleet request and clicking the instances.

Please provide the status of the fleet request and the spot instances, and I can help you from there.

**Comment by Baesm** [comment]
looking at the spot instances was the right way to go. As you can see, I get an "spotInstanceCountLimitExceeded" error, but a first glance at the limits seems like I am allowed to create at least one spot instance. I'll keep you updated, at least I know its an aws thing. I am not able to get a spot instance for all three different systems. 

<img width="898" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54865639-c21b0900-4d68-11e9-90f3-52123722f8d4.png">

**Comment by c6fc** [comment]
Hi Baesm,

Thanks for sharing your results. By default, the limit for GPU Spot instances on new AWS accounts is 1. In order to start larger campaigns, you'll need to request that increase. Make sure you request a limit increase for SPOT instances (the limit screenshot you posted shows 'on-demand'), for all g3, p2, and p3 instance types, for regions us-west-1, us-west-2, us-east-1, and us-east-2.

Put in that limit request, and let me know if this error persists. Meanwhile, I'll see if I can get the dashboard to update on errors like this. Thanks again for sharing!

**Comment by swarleysez** [comment]
Thanks for your quick replies on this.  I do have the SPOT instance limit issue (limit of 1) and I just requested an increase across each type and region you have listed above.

My initial issue of not seeing SPOT requests being populated is because I wasn't switching between regions to view the ones selected for the campaign.
![image](https://user-images.githubusercontent.com/31361532/54867711-c7248c00-4d59-11e9-8a3c-16bfd38f2c28.png)

My other issue was that I had not accepted the AWS Marketplace opt-in for the GPU driver.
![image](https://user-images.githubusercontent.com/31361532/54867710-c12eab00-4d59-11e9-8d0a-72a2fdf82f34.png)

**Comment by c6fc** [comment]
Opting into the subscription is an important step, which is shown on the readme. Hopefully with the combination of spot limit increase and subscribing to the NVidia AMIs will get you fully up and running!

**Comment by Baesm** [comment]
Thanks very much for your feedback. I did follow the steps on the readme, so the nvidia opt-in was done. I do know now that „instances on demand“ aren‘t equal to „Spot instances“. Very important step that confused me at first (as an AWS beginner). I contacted Support to allow more spot instances, so I will update you again on the progress. Thanks a lot!

**Comment by Baesm** [comment]
Hello guys, some good news! First, my amazon spot instance limit was increased and I can now start spot instances properly as shown here in the event logs of the machine: 

<img width="1039" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54880324-e7307a00-4e43-11e9-892d-609cc04eef9c.png">

But, I got a new problem now. After about 10 minutes the UI updates to this error without me doing anything: 

<img width="978" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54880352-19da7280-4e44-11e9-8345-2f627b14cd4f.png">


I invested the places you named and found suspicious activity in the cloudwatch logs. A new request is logged there every minute without me starting/running/canceling campaigns: 

<img width="1039" alt="grafik" src="https://user-images.githubusercontent.com/21155499/54880380-55753c80-4e44-11e9-8b37-997fce2e6dcd.png">


For now I will do a complete reinstall. Wish me luck, we are getting closer! And again, thanks a lot!

**Comment by c6fc** [comment]
Hi Baesm,

That's actually a good sign - that means that the campaign is running through it's full lifecycle now. 'User initiated termination' happens after Hashcat stops running on the node and it shuts itself down. The only problem is that the node is shutting down before posting a status update.

One of two things is happening now:

1. The campaign is so quick that it finishes in less than 30 seconds, before a status update is able to post.
2. The hashfile you uploaded isn't valid, which causes hashcat to error out right after the node starts.

To find out, go to 'File Management' and check for a file that starts with 'cracked-hahes'. If that file exists, it means the campaign finished successfully. If not, check the file and ends in 'output.log', which is the debug output for the cracking node.

![Selection_081](https://user-images.githubusercontent.com/143415/54882431-960e8f00-4e1f-11e9-99f6-bc353e5f17ee.png)

If you scroll all the way to the bottom, you should see the hashcat command with all it's parameters:

![Selection_080](https://user-images.githubusercontent.com/143415/54882441-b50d2100-4e1f-11e9-83e7-dfef471405f7.png)

Do you see any errors after that?

**Comment by c6fc** [comment]
Also, from where you are you don't need to re-install. Everything is set up right, it's just a matter of setting up a functional campaign, which is the last step! Thanks for posting your progress through this, it will help other folks a lot down the road!

**Comment by Baesm** [comment]
found an error in the log data. This error persists in all logs. 

`Skipping maskprocessor
Credentials loaded
[ '--quiet',
  '-O',
  '--remove',
  '--potfile-path=/potfiles/i-0590f8a50b955f1ad.potfile',
  '-o',
  '/potfiles/cracked_hashes-i-0590f8a50b955f1ad.txt',
  '-w',
  '4',
  '-m',
  2500,
  '-a',
  3,
  '/root/hashes.txt',
  '?d?d?d?d?d?d?d?d' ]
Found status report in output
Caught error: TypeError: Cannot read property 'split' of undefined


Died with code 255 and signal 0

Dying words:




{ Error: ENOENT: no such file or directory, open '/potfiles/cracked_hashes-i-0590f8a50b955f1ad.txt'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Promise (/root/compute-node/hashcat_wrapper.js:198:28)
    at new Promise (<anonymous>)
    at sendFinished (/root/compute-node/hashcat_wrapper.js:192:9)
    at runHashcat.then (/root/compute-node/hashcat_wrapper.js:323:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/potfiles/cracked_hashes-i-0590f8a50b955f1ad.txt' }
Completed 95.9 KiB/95.9 KiB (207.5 KiB/s) with 1 file(s) remaining
upload: ../potfiles/i-0590f8a50b955f1ad-output.log to s3://npk-user-data-20190324142143293200000010/us-west-2:fd5fb6ef-1df7-48af-b300-27b95067af68/campaigns/2957a959-23e8-4f1a-8430-94f686b97517/potfiles/i-0590f8a50b955f1ad-output.log
Cloud-init v. 0.7.6 finished at Sun, 24 Mar 2019 15:02:58 +0000. Datasource DataSourceEc2.  Up 110.75 seconds`

**Comment by c6fc** [comment]
Thanks for sharing. I'm looking into it now.

**Comment by c6fc** [comment]
@Baesm it looks like the NPK is fully running for you, but it looks like there's a bug with hccapx files getting mangled when they're uploaded to S3, which makes Hashcat error out. 

I've fixed the issue with the wrapper not posting a failure update, so you should now properly see the nodes error out when this happens.

I'll open a separate issue to track the problem with hccapx files.

**Comment by c6fc** [comment]
#7

**Comment by Baesm** [comment]
Yes thank you very much, this Issue is closed. Thanks a lot and hopefully this will help future researchers.

**Comment by c6fc** [comment]
@Baesm the fix for the underlying issue has been pushed. WPA2 with hccapx files works again!

![Selection_087](https://user-images.githubusercontent.com/143415/54884805-d0395a00-4e3a-11e9-891b-4a736ff9e32f.png)
