### ISSUE TITLE
Race condition in potfiles sync

### ISSUE THREAD

**Issue by tomtoump** [Coalfire-Research/npk#51]
The lines below create a race condition that results in some cracked passwords being lost, in the case that the upload is executed before the download.

https://github.com/Coalfire-Research/npk/blob/8ed3b47ad778bbbc2806789a2fbc0c2b7adf4b28/terraform/templates/userdata.tpl#L75-L76

What is the purpose of downloading the potfiles in the first place?

**Comment by c6fc** [comment]
Ahh, I see what you mean. Instead, this should be modified to run the commands in series. Good catch.

**Comment by c6fc** [comment]
Fixed in 02a72e8
