### ISSUE TITLE
Node JS 6.10/8.10 Error

### ISSUE THREAD

**Issue by ngr-1** [Coalfire-Research/npk#52]
The following error is given when attempting to run ./deploy
Error: Error applying plan:

3 error(s) occurred:

* aws_lambda_function.spot_monitor: 1 error(s) occurred:

* aws_lambda_function.spot_monitor: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions.
	status code: 400, request id: d577017a-ea21-4af6-944f-cff132efa4f1
* aws_lambda_function.status_reporter: 1 error(s) occurred:

* aws_lambda_function.status_reporter: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions.
	status code: 400, request id: 441a1909-db28-4c5e-b9e1-11202899129e
* aws_lambda_function.proxy_api_handler: 1 error(s) occurred:

* aws_lambda_function.proxy_api_handler: Error creating Lambda function: InvalidParameterValueException: The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs10.x) while creating or updating functions.
	status code: 400, request id: e23a7ae5-9924-4d61-b961-a809fd8dc7c1

**FIX**:

Find and replace "6.10" with "10.x" in /npk/terraform/jsonnet/lambda_functions.libsonnet

**Comment by c6fc** [comment]
These were updated to 8.10 back in May with eebc6d6

**Comment by bzekanovic** [comment]
**I got this from AWS not long ago.** 

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Node.js 8.10, which will reach its EOL at the end of 2019.

> What’s happening?

The Node community has decided to end support for Node.js 8.x on December 31, 2019 [1]. From this date forward, Node.js 8.x will stop receiving bug fixes, security updates, and/or performance improvements. To ensure that your new and existing functions run on a supported and secure runtime, language runtimes that have reached their EOL are deprecated in AWS [2].

For Node.js 8.x, there will be 2 stages to the runtime deprecation process:

1. Disable Function Create – Beginning January 6, 2020, customers will no longer be able to create functions using Node.js 8.10

2. Disable Function Update – Beginning February 3, 2020, customers will no longer be able to update functions using Node.js 8.10

After this period, both function creation and updates will be disabled permanently. However, existing Node 8.x functions will still be available to process invocation events.

> What do I need to do?

We encourage you to update all of your Node.js 8.10 functions to the newer available runtime version, Node.js 10.x[3] or Node.js 12.x[4]. You should test your functions for compatibility with either the Node.js 10.x or Node.js 12.x language version before applying changes to your production functions.

**Comment by c6fc** [comment]
AWS prevents the creation of Lambda functions using deprecated runtimes. Ensuring these function with 10.x runtime is already underway, and the master branch will be updated once that's done.
