### ISSUE TITLE
Invalid routes 

### ISSUE THREAD

**Issue by mastercho** [Coalfire-Research/npk#54]
Getting this error in deployment

````
Error: Incorrect attribute value type

  on routetable.tf.json line 28, in resource.aws_route_table.us-west-1:
  28:             "route": {
````

for every route in routetable.tf.json

**Comment by bzekanovic** [comment]
Make sure you are using Terraform version below < 12 https://releases.hashicorp.com/terraform/

**Comment by mastercho** [comment]
> Make sure you are using Terraform version below < 12 https://releases.hashicorp.com/terraform/

downgraded to 11 and now getting a different error
```Error: Error parsing /npk/terraform/cloudwatch-policy.tf: At 18:7: unexpected token while parsing list: IDENT```

**Comment by mastercho** [comment]
https://github.com/Coalfire-Research/npk/issues/24 saw it here and fixed after recloning
