### ISSUE TITLE
Vbulletin hash type

### ISSUE THREAD

**Issue by mastercho** [Coalfire-Research/npk#55]
When i choose md5(md5($pass)$salt) AKA VBulletin < v3.8.5 hash type i got `???` in instance estimate and in summary 

> f (Fubar. Something is wrong.)

**Comment by c6fc** [comment]
It sounds like you haven't specified a wordlist, rules, or mask yet. You have to finish specifying the config before the options will work.

If you have these selected, and are still having the same issue, please upload a screenshot of the campaign configuration. Thanks
