### ISSUE TITLE
Custom Wordlist Issue / Fix

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#57]
Following the guide to configure NPK with custom wordlist will leave your UI spinning when it tries to pull the new list from the bucket. The fix is to re-upload your site content via AWS command provided via NPK. @c6fc  can you update your docs to include this?

**Comment by ddarshan25** [comment]
Can you share link to add custom wordlist ?

**Comment by swarleysez** [comment]
For anyone not sure, the AWS command referenced above looks like this:
`aws --profile npk s3 --region us-west-2 sync /opt/npk/terraform/../site-content/ s3://npk-site-content-<timestamp>`

It is output at the end of every "./deploy.sh" execution. Be patient, at it might take a few minutes for the content to update on the site.

**Comment by swarleysez** [comment]
While the update to the site did work. I'm getting "Invalid date" under "Total Duration". My rules and wordlists are in the formatting specified by the wiki.

![image](https://user-images.githubusercontent.com/31361532/68551067-f5cda080-03d6-11ea-9e83-d2c8fb5bc30b.png)

**Comment by c6fc** [comment]
I updated the wiki to recommend calling `$(terraform output s3_static_site_sync_command)` after running deploy. This will force a resync of the site content so that it references the custom wordlist buckets.
