### ISSUE TITLE
Can't see high power instances

### ISSUE THREAD

**Issue by ddarshan25** [Coalfire-Research/npk#60]
Hi,

I have recently deployed NPK and wanted to use for Internal and external Pen tests, but i am not able to see high power instances, see the screenshot below:

I don’t see the really big GPU instances in the console.  

We were expecting to see:
![npkexpected](https://user-images.githubusercontent.com/14995478/67832273-22480980-fb07-11e9-993a-5c50e3b4d26c.png)

What we see is:
![npk](https://user-images.githubusercontent.com/14995478/67832253-0f353980-fb07-11e9-90b6-eecf817ac754.png)

 Please let me know , how to get high powered instances.

Thanks,
Dhruva

**Comment by ddarshan25** [comment]
Hey @dsopas , i have requested amazon ec2 and they have approved my request to increase spot instances. But still i see same instances. Should i restart the VM hosting NPK to see the changes ?

Thanks for your help.

**Comment by szakos201** [comment]
I have the same issue.

**Comment by szakos201** [comment]
I have changed the lt sign (before `result.gpus`) to gt and now i see the high power instances.

https://github.com/Coalfire-Research/npk/blob/8ed3b47ad778bbbc2806789a2fbc0c2b7adf4b28/site-content/angular/controllers/npkMainCtrl.js#L638

**Comment by ddarshan25** [comment]
i did that and ran deploy.sh, but i still dont see any changes.

**Comment by c6fc** [comment]
An alternative view has been added with 2608dbc to allow overriding pricing suggestions and pick arbitrary instance types within specific regions.
