### ISSUE TITLE
Tool installed as instructed and running fine, but not executing and result showed 0 in cracked hashed.

### ISSUE THREAD

**Issue by Leectan** [Coalfire-Research/npk#66]
Tool running for 7 hours, but no result after running at P3.8xlarge instance. Result showing 0 cracked hashes and 50 provisioning years, success rate at 0.00%. 

If someone could explain what's going on would be great.

**Comment by c6fc** [comment]
I'm not sure what you mean by '50 provisioning years' - can you provide a screenshot?
Did you see the progress indicators of the nodes/GPUs in the dashboard while the campaign was in progress?

0.00% success rate means that it didn't manage to crack any of the hashes you uploaded using the campaign you configured. If there are no errors, it just means that you have to try a different approach; this could be alternative dictionaries, rule files, or masks.
