### ISSUE TITLE
Add An Open Source License 

### ISSUE THREAD

**Issue by KyleEvers** [Coalfire-Research/npk#67]
Per [Github's License Page](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository): 

`
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.
`

[Choosing a license](https://choosealicense.com/) protects contributors/users and gives concrete rules for what can and cannot be done with the code.

**Comment by mcdonnnj** [comment]
Given that the [release blog post](https://www.coalfire.com/The-Coalfire-Blog/March-2019/High-Power-Hash-Cracking-with-NPK) states that:

> NPK is open-sourced at https://github.com/Coalfire-Research/npk and is deployed just for you, entirely within AWS.

I think it is important for there to be a license in the repository to very clearly articulate what is meant by open-source for this project. Although I understand the sentiment of just saying something is open-source, a lack of licensing can prevent more widespread usage and improvement in the community due to the fundamental differences in open source licenses commonly used.

**Comment by c6fc** [comment]
I'm reviewing options and will include a license soon.

**Comment by jsf9k** [comment]
A license would be help lead to more widespread adoption.  A lot of organizations have legal departments that won't use software advertised as open source unless the licensing is clear.

**Comment by felddy** [comment]
This seems like a great project.  We'd love to use it but, alas, I see no [license](https://github.com/Coalfire-Research/npk/blob/master/LICENSE)...  which implies [all rights are being reserved](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license)... 

![3pso5s](https://user-images.githubusercontent.com/3229435/74969600-dccb8700-53ea-11ea-844e-59e8184f16cf.jpg)

**Comment by Essex09** [comment]
Any update on when you'll be adding a license?

**Comment by KyleEvers** [comment]
@c6fc Any update on this?

**Comment by awhitehatter** [comment]
Hi @KyleEvers , I'm on this today, thanks for posting this.

**Comment by awhitehatter** [comment]
Added GNU GENERAL PUBLIC LICENSE - Version 3, thanks again for the request.
