### ISSUE TITLE
Wrong node JS version on install

### ISSUE THREAD

**Issue by vaguely-tagged** [Coalfire-Research/npk#68]
On install, NPK  is forcing an old version of nodejs(8) but aws requires >12

This makes the installation
<img width="1067" alt="Screen Shot 2020-01-12 at 9 47 51 PM" src="https://user-images.githubusercontent.com/20882530/72235116-35566b80-3585-11ea-899f-9acb826c6b43.png">
 fail.

**Comment by destrome** [comment]
why is this closed? it's a valid issue preventing deployment?

**Comment by vaguely-tagged** [comment]
I ended up fixing it myself by editing all the node 8 values to 12

**Comment by destrome** [comment]
fair. thanks for the tip
