### ISSUE TITLE
Password Cracking Results Inconsistent

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#71]
Hello @c6fc 

I've noticed that NPK is inconsistent when it comes to results of passwords cracked and it seems to be all pointing to number of hashes being uploaded. Keep in mind that both scenarios below are using same wordlist / rules and hashtype - 13100. 

**Scenario 1 - NPK  - 2 Separate GPU Instances**
Hashes Uploaded - 53
Cracked Passwords = 1

**Scenario 2 - NPK - 2 Separate GPU Instances - Took Hashes from Scenario 2 and split them into 2 files / 2 different jobs**
**Job 1** 
Hashes Uploaded 39
Cracked Passwords = 0

**Job 2** 
Hashes Uploaded - 14
Cracked Passwords = 4

It would be great to narrow down if this is caused by number of hashes being uploaded or something else. 

Thanks,

**Comment by c6fc** [comment]
Would you be willing to provide me the hashfile so I can troubleshoot?

Have you noticed this behavior with any hashtype other than 13100?

**Comment by bzekanovic** [comment]
@c6fc  I can't provide you with hashfile for 13100. 
Also, I am also testing this with 5600 hashtype to see if I can replicate this same issue.

**Comment by bzekanovic** [comment]
@c6fc  

Ran NPK job with 5600 hash type with 3 hashes and I got same results as my local rig. 

Can you try to replicate this issue with 13100 hash type on your side? 
Are there specific logs I should check to see if any errors are showing up when running NPK job with my 13100 scenario above?

Thanks,

**Comment by bzekanovic** [comment]
@c6fc 
This issue might be related to choosing low spec GPU instances for hashes that require a lot more GPU memory. I ran the same job with high spec GPU instance and I was able to get same results as local rig. I'll let you know if anything changes during further testing.

**Comment by bzekanovic** [comment]
@c6fc 

It would be great if we can turn this issue into feature request where NPK can select preferred instance types per hash type selected. This way NPK will only show higher GPU specs instances when certain hashes are selected. 

Thanks,

**Comment by c6fc** [comment]
@bzekanovic if hashes aren't getting cracked because of insufficient GPU memory, this would be a problem with Hashcat and not with NPK.

The v2 branch has an advanced instance selection menu where you can force the selection of any size of GPU instance. Give that a shot and see if it makes a difference, and if it does, consider reporting the discovery to the Hashcat devs.

**Comment by bzekanovic** [comment]
@c6fc  thank you and I will check out the v2. When do you think you will have official V2 out and do you think you can provide some insight what features we should expect to see?
