### ISSUE TITLE
Europe deployment

### ISSUE THREAD

**Issue by Sn00z3r** [Coalfire-Research/npk#72]
Dear,

Is possible to deploy only on European availability zones (e.g. eu-west)?

Best regards!

**Comment by c6fc** [comment]
I'm doing a pretty substantial rewrite with v2 to allow more control over which AZs are supported. I'll make sure to test with non-us regions to make sure they can be used.

**Comment by Kadeeli** [comment]
This would be awesome!

**Comment by dak-csis** [comment]
I have attempted to manually re-write npk to work in europe but, due to my complete lack of knowledge, i failed. I managed to get the entire thing deployed in eu-central and having the web interface run. It just wouldn't crack anything.

**Comment by c6fc** [comment]
Tracking in #50
