### ISSUE TITLE
Unable to start new campaign

### ISSUE THREAD

**Issue by doyler** [Coalfire-Research/npk#77]
When I attempt to start a new campaign, I get the following error:

`AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet `

Upon checking the CloudWatch logs for proxy_api_handler, I see the same error.

`2020-02-19T22:05:44.833Z	e206aece-a30f-4f26-a344-ec623df01648	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error requesting spot fleet: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.",
    "reason": "Error requesting spot fleet: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.",
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error requesting spot fleet: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:223:5)",
        "    at process.EventEmitter.emit (domain.js:475:20)",
        "    at processPromiseRejections (internal/process/promises.js:201:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:32)"
    ]
}
`

I'm assuming this is relating to one of the roles missing the iam:CreateServiceLinkedRole action, but I added it to both npk_fleet_role_policy as well as npk_lambda_api_handler_role to no avail. I also created the AWSServiceRoleForEC2Spot Service-Linked role, in case that was necessary.

Any ideas/suggestions/changes that need to be made?

**Comment by c6fc** [comment]
Can you DM me the output from `deploy.sh` from prior to the terraform apply? I'm specifically interested in the output following:

[+] Creating service-linked roles for EC2 spot fleets

**Comment by doyler** [comment]
Just posting it here for now, since it was an error that someone else could come across!

`
[*] Checking service-linked roles for EC2 spot fleets

An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
`

**Comment by c6fc** [comment]
Is there a line like this? If so, there are four commands that are run to create the AmazonEC2SpotFleetRole, and you should see the output from those four commands. Include them as well if you can.

[+] Creating service-linked roles for EC2 spot fleets

**Comment by doyler** [comment]
Yup, my apologies. There was only a reference for "Checking" not "Creating". That said, it looks to be because line 51 doesn't receive the expected value.

`# aws --profile NPKuser iam get-role --role-name AmazonEC2SpotFleetRole

An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
# echo $?
254`

**Comment by c6fc** [comment]
That's odd. What version of the AWSCLI are you using?

Also, if you modify that conditional at line 61 to be 254, does the deploy occur successfully, and give you the ability to launch campaigns?

**Comment by doyler** [comment]
```
$ aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/18.7.0 botocore/2.0.0dev4
```

Destroying and rebuilding everything with that change may have worked!

"Success: Campaign started successfully"

Update: Nope, looks like it STILL didn't actually create the necessary roles.

```
Repeated errors have occurred processing the launch specification "p3.8xlarge, ami-09144ebbb8d7191e3, Linux/UNIX, us-east-1f while launching spot instance". It will not be retried for at least 13 minutes. Error message: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances. (Service: AmazonEC2; Status Code: 403; Error Code: AuthFailure.ServiceLinkedRoleCreationNotPermitted)
```

I had to DELETE the roles (to get the 254 again instead of 0), destroy the Terraform, manually delete other stuff, and then run deploy.sh again. It looks like the destroy isn't removing those roles, so things may get wonky if you try to re-deploy, especially with that conditional.

That said, it looks like it is still failing even after creating the roles?

```
The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances. (Service: AmazonEC2; Status Code: 403; Error Code: AuthFailure.ServiceLinkedRoleCreationNotPermitted)
```

```
[+] Creating service-linked roles for EC2 spot fleets
{
    "Role": {
        "Path": "/",
        "RoleName": "AmazonEC2SpotFleetRole",
        "RoleId": "AROA3SFWP3UTY2257MJ5X",
        "Arn": "arn:aws:iam::794951671079:role/AmazonEC2SpotFleetRole",
        "CreateDate": "2020-02-20T20:46:40+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "",
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "spotfleet.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        }
    }
}
{
    "Role": {
        "Path": "/aws-service-role/spot.amazonaws.com/",
        "RoleName": "AWSServiceRoleForEC2Spot",
        "RoleId": "AROA3SFWP3UTXWRELEHHW",
        "Arn": "arn:aws:iam::794951671079:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot",
        "CreateDate": "2020-02-20T20:46:45+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "sts:AssumeRole"
                    ],
                    "Effect": "Allow",
                    "Principal": {
                        "Service": [
                            "spot.amazonaws.com"
                        ]
                    }
                }
            ]
        }
{
    "Role": {
        "Path": "/aws-service-role/spotfleet.amazonaws.com/",
        "RoleName": "AWSServiceRoleForEC2SpotFleet",
        "RoleId": "AROA3SFWP3UTVXIANNBVR",
        "Arn": "arn:aws:iam::794951671079:role/aws-service-role/spotfleet.amazonaws.com/AWSServiceRoleForEC2SpotFleet",
        "CreateDate": "2020-02-20T20:46:48+00:00",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": [
                        "sts:AssumeRole"
                    ],
                    "Effect": "Allow",
                    "Principal": {
                        "Service": [
                            "spotfleet.amazonaws.com"
                        ]
                    }
                }
            ]
```

**Comment by StuartDuncan** [comment]
I had this issue but it was when trying to deploy using access keys from a root account

**Comment by c6fc** [comment]
@doyler can you confirm whether or not you were running deploy with root account creds or an IAM user?

**Comment by KyleEvers** [comment]
I have seen a similar issue that was related to the EC2 resource limits for the GPU instances. When you try and launch an additional campaign when a previous one is not completely terminated. 

For example if your resource limit for a `p3.8xlarge` is 1 instance and you launch 2 consecutive campaigns or one is still shutting down when you launch a second you will receive an error similar to the aforementioned:
```bash 
Repeated errors have occurred processing the launch specification "p3.8xlarge, ami-09144ebbb8d7191e3, Linux/UNIX, us-east-1f while launching spot instance". It will not be retried for at least 13 minutes. Error message: The provided credentials do not have permission to create the service-linked role for EC2 Spot Instances. (Service: AmazonEC2; Status Code: 403; Error Code: AuthFailure.ServiceLinkedRoleCreationNotPermitted)
```
Because even though the role has the permissions to request the additional EC2 the account does not have permission to exceed the resource limit.  

The solution to this is just [request a limit increase](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html) for all the GPU EC2 instances. Upon requesting limit increases I haven't seen this error again. 

Perhaps give this a shot if your issue persists.

**Comment by doyler** [comment]
I was running deploy with an IAM user in my ~/.aws/credentials file.

I did see that error, but that was after the fact.

**Comment by copacetic** [comment]
I am seeing the exact same error fwiw. I am not running as root.

**Comment by bigpick** [comment]
I've just run into the same issue as well;
* `AuthFailure.ServiceLinkedRoleCreationNotPermitted` in the console when trying to start the only created campaign
* Before then, as part of the `./deploy.sh` run, a message like
    ```
    [*] Checking service-linked roles for EC2 spot fleets

    An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
    ```
    and, when checking manually, response code also showed 254:

    ```
    aws --profile <profile> iam get-role --role-name AmazonEC2SpotFleetRole
    An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
    
    echo $?
    254
    ```

I cancelled the un-startable campaign in the UI, and then tore down the rest of the deploy with `terraform destroy`. Then updated `deploy.sh` conditional line to be 254 (instead of the 255 it was):

```
aws --profile $(jq -r '.awsProfile' npk-settings.json) iam get-role --role-name AmazonEC2SpotFleetRole > /dev/null
-if [[ $? -eq 255 ]]; then
+if [[ $? -eq 254 ]]; then
    echo "[+] Creating service-linked roles for EC2 spot fleets"
```

and re-tried `./deploy.sh`, and still, time around, when trying to start a campaign:

```
  Error: Error requesting spot fleet: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.
```

**Comment by bigpick** [comment]
I've just run into the same issue as well (root acct);
* `AuthFailure.ServiceLinkedRoleCreationNotPermitted` in the console when trying to start the only created campaign
* Before then, as part of the `./deploy.sh` run, a message like
    ```
    [*] Checking service-linked roles for EC2 spot fleets

    An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
    ```
    and, when checking manually, response code also showed 254:

    ```
    aws --profile <profile> iam get-role --role-name AmazonEC2SpotFleetRole
    An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
    
    echo $?
    254
    ```

I cancelled the un-startable campaign in the UI, and then tore down the rest of the deploy with `terraform destroy`. Then updated `deploy.sh` conditional line to be 254 (instead of the 255 it was):

```
aws --profile $(jq -r '.awsProfile' npk-settings.json) iam get-role --role-name AmazonEC2SpotFleetRole > /dev/null
-if [[ $? -eq 255 ]]; then
+if [[ $? -eq 254 ]]; then
    echo "[+] Creating service-linked roles for EC2 spot fleets"
```

and re-tried `./deploy.sh`. (first, [disabled the pager](https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html)), now, when running, I see:

```
[*] Checking service-linked roles for EC2 spot fleets

An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
[+] Creating service-linked roles for EC2 spot fleets
{
    "Role": {
        "Path": "/",
        "RoleName": "AmazonEC2SpotFleetRole",
        ...
}
{
    "Role": {
        "Path": "/aws-service-role/spot.amazonaws.com/",
        "RoleName": "AWSServiceRoleForEC2Spot",
        ...
{
    "Role": {
        "Path": "/aws-service-role/spotfleet.amazonaws.com/",
        "RoleName": "AWSServiceRoleForEC2SpotFleet",
        ...
}
[*] Retrieving AWS credentials from profile
[*] Generating combined settings file
...
```
And now this time around:
> Success: Campaign started successfully

**Comment by blark** [comment]
I'm having the exact same issue here, `deploy.sh` outputs this when starting up: 

```
 $ ./deploy.sh
[*] Preparing to deploy NPK.
[*] Getting availabilityzones from AWS
[*] - us-east-1
[*] - us-east-2
[*] - us-west-1
[*] - us-west-2
[*] Checking service-linked roles for EC2 spot fleets

An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
[*] Retrieving AWS credentials from profile
```

To confirm, I created an organization and then added a new account as per the docs, and created API access keys with that new account (and then configured "awsProfile" in npk-settings.json to use it).

**Comment by c6fc** [comment]
I changed the logic around this in v2 to simply call the CreateServiceLinkedRole action without trying to check whether a role already exists or not. It has a hacky attempt to only call it once by only running if terraform hasn't been initialized, but since the action will fail if it already exists, it's effectively idempotent.
