### ISSUE TITLE
After deploy only able to access through cloudfront URL/not custom domain

### ISSUE THREAD

**Issue by mkannan22** [Coalfire-Research/npk#78]
Deployed and everything ran run using the long cloudfront URL to access NPK. However, every time I deploy this is the only way I can access NPK. I can't use the actual domain name that's listed in my public zone, which is the same one that NPK emails me. I always recieve the {"message":"Forbidden"} when trying to browse to that URL (i.e. https://example.com) shows this message, but when entering https://example.cloudfront.net, NPK loads successfully. Is this by design or should I be able to access the URL I created in the hosted zone. I have my country whitelisted and received the following errors each time I run the deploy script.

Error: Error applying plan:

2 error(s) occurred:

* aws_route53_record.api-record-0: 1 error(s) occurred:

* aws_route53_record.api-record-0: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='example.com.', type='A'] but it already exists]
        status code: 400, request id: xxxxxxx-xxxxxxx-xxxxxxx-xxxxxxx
* aws_route53_record.acm-validation-www-0: 1 error(s) occurred:

* aws_route53_record.acm-validation-www-0: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='xxxxxxxxxxxxxxxx.example.com.', type='CNAME'] but it already exists]
        status code: 400, request id: xxxxxxxxx-xxxxxxxx-xxxxxxx-xxxxxx

**Comment by c6fc** [comment]
You're getting this error because you already have DNS validation records and ACM certificate for the domain name you're trying to assign to NPK.

Either change the domain name you're assigning so that NPK can create the Route53 records and ACM certificate, or remove the ACM certificate and route53 records to allow NPK to create them.
