### ISSUE TITLE
wordlist not being created

### ISSUE THREAD

**Issue by ActivateDZA** [Coalfire-Research/npk#8]
Hi,

I have an issue where the wordlists are not being created during the installation process
![image](https://user-images.githubusercontent.com/2852188/55090273-7e513800-50b7-11e9-9131-d19ebf19bb14.png)

I have attached a picture (I hope you can see it) where the wordlist attack is empty.

Also there are no errors during the installation process

**Comment by ActivateDZA** [comment]
Nevermind issue was between chair and computer. Figured it out.

**Comment by c6fc** [comment]
For those encountering this issue in the future, be sure you click 'Select' on one of the instances in the first row. The dictionaries will populate afterward.
