### ISSUE TITLE
Support for MSSQL Hashes

### ISSUE THREAD

**Issue by z3-al** [Coalfire-Research/npk#81]
I cannot see a listing for MSSQL hashes in the full "Hash Type" list when starting a new campaign - would be great if there was a way to support cracking of these hashes. Specifically, this is the following hash types for hashcat: 

ID | Type
131 | MSSQL (2000)
132 | MSSQL (2005)
1731 | MSSQL (2012, 2014)

Further, would be great if there was a search feature to choose the hash type rather than having to scroll through an exhaustive list! :)

**Comment by c6fc** [comment]
The v2 branch has an 'advanced view' in the dashboard that lets you put the ID instead of selecting the hashtype from a dropdown.
