### ISSUE TITLE
Errors on deploy.sh on v2 branch

### ISSUE THREAD

**Issue by mkannan22** [Coalfire-Research/npk#83]
parse error: Expected separator between values at line 20, column 11
aws: error: argument command: Invalid choice, valid choices are:
jq: error (at r4.json:0): null (null) and null (null) cannot be multiplied

**Comment by mkannan22** [comment]
If I run terraform init I see the following:

 terraform init
Error getting plugins: module root: 4 error(s) occurred:

* resource 'aws_s3_bucket_policy.s3_static_site' config: unknown resource 'aws_s3_bucket.static_site' referenced in variable aws_s3_bucket.static_site.id
* resource 'data.aws_iam_policy_document.cloudwatch_invoke_spot_monitor' config: unknown resource 'aws_lambda_function.spot_monitor' referenced in variable aws_lambda_function.spot_monitor.arn
* resource 'data.aws_iam_policy_document.s3_static_site' config: unknown resource 'aws_s3_bucket.static_site' referenced in variable aws_s3_bucket.static_site.arn
* resource 'data.aws_iam_policy_document.s3_static_site' config: unknown resource 'aws_cloudfront_origin_access_identity.npk' referenced in variable aws_cloudfront_origin_access_identity.npk.iam_arn

terraform --version shows
Terraform v0.11.0
+ provider.aws v2.53.0

Your version of Terraform is out of date! The latest version
is 0.12.23. You can update by downloading from www.terraform.io/downloads.html

**Comment by mkannan22** [comment]
Tested on Ubuntu 18.04 LTS and Kali 2020.1 without success.

**Comment by mkannan22** [comment]
installed jsonnet from google. tried both awscli 1.8 and 2.0. tried Terraform v0.11.14. no issues on dependencies, just the errors mentioned above anytime I try to deploy v2 branch.

**Comment by mkannan22** [comment]
Has anyone successfully deployed v2 and if so, what were your steps to get it running?

**Comment by marti2221** [comment]
im having a hell of a time as well. Ive got NPK installed and running, but once i attempt to start a campaign from the dash, i get an error.

**Comment by c6fc** [comment]
The first error you get seems to indicate that the deploy script is failing to enumerate the availability zones for us-west-2.

Comment out line 52 in the deploy.sh script, then inspect the contents of r1-r4 files. If one of them is empty (or missing), it's an indication that `ec2 describe-availability-zones` is failing for that region. Try running the describe-availability-zones command yourself, and paste the out put.

**Comment by marti2221** [comment]
where would the r1-r4 files be located? cant seem to find them. Also the
instructions instructed to subscribe to the AWS AMI instance, but makes no
mention of manually launching it, should i?

**Comment by marti2221** [comment]
actually ive now checked my spot instances and there are 2 running

**Comment by marti2221** [comment]
their state is "ACTIVE" but they're receiving many errors:
[image: Screen Shot 2020-03-26 at 12.17.34 PM.png]

**Comment by marti2221** [comment]
not sure if that img went through or not...

**Comment by marti2221** [comment]
its also now starting a campaign with no errors (console/network/cloudfare
logs). But campaign state hangs on "STARTING", the cost is always listed as
$0.00, and no updates have been made under the "No status reports received.
Nodes may still be starting" message. As i said in the last message, the
spot instances are full of errors as well.

**Comment by marti2221** [comment]
Hello, sorry to bother you again, but i have still been unsuccessful in my
attempts to run aws instances via NPK. The app says im running a successful
mission, but doesnt start any instances on AWS. There seems to be a prob
with roles (although AFAIK theyre all created). When looking at my logs, it
shows repeated "EXIT No fleet requests" and "Error Unhandled Promise
Rejection" in my spot_monitor log after running a campaign. The
proxy_api_handler seems to show a successful campaign launch. Any idea as
to what the prob could be?

**Comment by thalesredteam** [comment]
HELP PLEASE

[*] - us-east-1
parse error: Expected separator between values at line 17, column 11
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

**Comment by thalesredteam** [comment]
/npk/terraform# aws --profile $(jq -r '.awsProfile' npk-settings.json) ec2 --region us-east-2 describe-availability-zones | jq '{"us-east-2": [.AvailabilityZones[] | select(.State=="available") | .ZoneName]}' > r2.json

parse error: Expected separator between values at line 17, column 11
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

**Comment by thalesredteam** [comment]
jq -r '.awsProfile' npk-settings.json

oh here's the problem
