### ISSUE TITLE
Error: Too many active campaigns.

### ISSUE THREAD

**Issue by mkannan22** [Coalfire-Research/npk#84]
When trying to run more than 1 campaign at a time I receive 

	Error: Too many active campaigns.

How do I run multiple campaigns at the same time and get past this error.

**Comment by mkannan22** [comment]
My AWS limit is up to 20 per month across 4 regions and I'm currently only running one campaign. I have tried forcing different regions as well, but the same error appears. Any guidance on where to look for additional errors or why I can only run one campaign at a time?

**Comment by bzekanovic** [comment]
One campaign per user is built into the code. You can change the source code and comment out campaign validation in https://github.com/Coalfire-Research/npk/blob/master/terraform/lambda_functions/proxy_api_handler/main.js if you really need to run more than one campaign. Another option is to submit issue / feature request to allow multiple campaigns. 


			if (i.active) {
				respond(429, "Too many active campaigns.", false);
				return Promise.reject('Too many active campaigns');
			}

**Comment by mkannan22** [comment]
Thank you.
