### ISSUE TITLE
hashFileUrl Error when campaign started

### ISSUE THREAD

**Issue by marti2221** [Coalfire-Research/npk#85]
I have managed a successful NPK install and campaign creation. However when i try to "start" the campaign, I get the following popup error: 

         "Error: hashFileUrl must be valid for at least 900 seconds, got -14415"(value varies but 
always negative)

<img width="657" alt="Screen Shot 2020-03-25 at 10 54 10 PM" src="https://user-images.githubusercontent.com/24699801/77609114-7e1b9080-6ef5-11ea-864e-bd39dca97005.png">

When looking @ the networking tab in the browser tools, it shows a 400 error stemming from a .send() method in the jquery.min.js file to this url: 

  "https://d4v48pajq6.execute-api.us-west-2.amazonaws.com/v1/userproxy/campaign/27543377-11fc-4540-af71-e6dcce712bd2" 

The proxy_api_handler log shows the same error repeatedly: 
 
         "ERROR	Unhandled Promise Rejection"

<img width="1079" alt="Screen Shot 2020-03-25 at 10 51 40 PM" src="https://user-images.githubusercontent.com/24699801/77615366-92678980-6f05-11ea-8bf2-8d84768c6b30.png">

I noticed from reading the deploy file that in line 50, the code states that the get-role command is used to add the AmazonEC2SpotFleetRole, then a few more roles/policies are added. Line 52 should write to the console: [+] Creating service-linked roles for EC2 spot fleets
This is not being triggered so i can only assume the following roles/policies aren't either. I did trying manually installing those roles. Which SEEMED to work, but still no execution of line 52 and still no campaign starting. No e2c instances launched in AWS account, no potfiles on NPK, Im stumped.

**Comment by c6fc** [comment]
The error you're seeing occurs when the campaign you create waits too long before being launched. When creating the campaign, the hashFileURL is a pre-signed URL that is only good for an hour, so if you wait more than 45 minutes (or if your system time is more than an hour off), the hashFileURL you create expires, and the campaign can no longer be started.

In your case, it looks like it had been expired for almost 4 hours. Make sure your system time and timezone are correct, then delete the campaign, recreate it, and immediately click 'Start' after creating. Let me know if the issue persists.

**Comment by marti2221** [comment]
It appears as though my date and time on my macbook are correct (Thur Mach 26, 2020; 11:17AM local time).

**Comment by marti2221** [comment]
some of my regional settings i believe were set as us-west-2 though, could that have something to do with it?

**Comment by awhitehatter** [comment]
Did you retry creating the campaign, then immediately click start?

**Comment by marti2221** [comment]
yes, however after requesting a limit increase on my AWS account, it seems
to have fixed the errors. Will have to confirm when I get home though.
Thank you for the response, ill get back to you as soon as i can.
