### ISSUE TITLE
[NEED HELP] ERRORS when trying to deploy! 

### ISSUE THREAD

**Issue by Mouadox** [Coalfire-Research/npk#86]
When trying to deploy using ./deploy.sh, I face the errors down below after a while, and the deploy process seems to be stuck in a loop, e.g  "aws_lambda_function.spot_monitor: Still creating..." again and again! 

3 error(s) occurred:

* aws_lambda_function.status_reporter: 1 error(s) occurred:

* aws_lambda_function.status_reporter: Error creating Lambda function: InvalidSignatureException: 
        status code: 403, request id: 51b321a9-23c8-42ca-b942-c75d83446a26
* aws_lambda_function.proxy_api_handler: 1 error(s) occurred:

* aws_lambda_function.proxy_api_handler: Error creating Lambda function: InvalidSignatureException: 
        status code: 403, request id: 32b795bb-64b2-47a2-907a-2f62f1a1c540
* aws_lambda_function.spot_monitor: 1 error(s) occurred:

* aws_lambda_function.spot_monitor: Error creating Lambda function: InvalidSignatureException: 
        status code: 403, request id: ff312b64-e3ca-4d56-b93b-ddd076a2da8c

However, I received the npk invitation email, but when I access the given link, this appears: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>952D8B6CEE4C7EBE</RequestId>
<HostId>
55SFcTmu0sEyiyftiEGm+y7iAx/VRr8BQNTmZNPo+5RZMMZPaegcHw8eEavcUlAAcElvsDgl2mk=
</HostId>
</Error>

I really NEED your HELP!

**Comment by marti2221** [comment]
i dont think this project is active. looks like several people are having similar, or the same issue. I didn't get a response, neither did the user who posted an issue last week. seems like this project just isnt up to date.

**Comment by awhitehatter** [comment]
@Mouadox , @marti2221  thank you for reporting your issues. This project is very much an active project. However, we've been slammed working on some other projects, so we under the weight of some backlog at the moment. 

It appears there's a known timing bug w/Terraform, causing invalid signature. Did the deploy script create the 3 lambda functions?

**Comment by romperchomper** [comment]
> When trying to deploy using ./deploy.sh, I face the errors down below after a while, and the deploy process seems to be stuck in a loop, e.g "aws_lambda_function.spot_monitor: Still creating..." again and again!
> 
> 3 error(s) occurred:
> 
>     * aws_lambda_function.status_reporter: 1 error(s) occurred:
> 
>     * aws_lambda_function.status_reporter: Error creating Lambda function: InvalidSignatureException:
>       status code: 403, request id: 51b321a9-23c8-42ca-b942-c75d83446a26
> 
>     * aws_lambda_function.proxy_api_handler: 1 error(s) occurred:
> 
>     * aws_lambda_function.proxy_api_handler: Error creating Lambda function: InvalidSignatureException:
>       status code: 403, request id: 32b795bb-64b2-47a2-907a-2f62f1a1c540
> 
>     * aws_lambda_function.spot_monitor: 1 error(s) occurred:
> 
>     * aws_lambda_function.spot_monitor: Error creating Lambda function: InvalidSignatureException:
>       status code: 403, request id: ff312b64-e3ca-4d56-b93b-ddd076a2da8c


I was having the same issue on Lubuntu 19.04. Updating my NodeJS from 10.x to 12.16 seemed to solve it.
