### ISSUE TITLE
deploy.sh - multiple errors

### ISSUE THREAD

**Issue by glwallum** [Coalfire-Research/npk#88]
I am recieving some errors when running deploy.sh. Below are my environment versions
Ubuntu 18.04
aws-cli/2.0.8 Python/3.7.3 Linux/4.15.0-1057-aws botocore/2.0.0dev12
Terraform v0.11.0
jq-1.5-1-a5b5cbe
npm 3.5.2
jsonnet v0.15.0

I have attached the output of the deploy, below are the errors
An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name AmazonEC2SpotFleetRole cannot be found.
5 error(s) occurred:

* aws_dynamodb_table.settings: 1 error(s) occurred:

* aws_dynamodb_table.settings: error creating DynamoDB Table: ResourceInUseException: Table already exists: Settings
* aws_dynamodb_table.campaigns: 1 error(s) occurred:

* aws_dynamodb_table.campaigns: error creating DynamoDB Table: ResourceInUseException: Table already exists: Campaigns
* aws_key_pair.us-west-2: 1 error(s) occurred:

* aws_key_pair.us-west-2: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'npk-key' already exists.
        status code: 400, request id: cdcc4e57-3381-4e29-ab21-dab2b56f7cfd
* aws_key_pair.us-east-1: 1 error(s) occurred:

* aws_key_pair.us-east-1: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'npk-key' already exists.
        status code: 400, request id: 05af75da-caa7-4f20-afc6-10aad9ffaa20
* aws_key_pair.us-west-1: 1 error(s) occurred:

* aws_key_pair.us-west-1: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'npk-key' already exists.
        status code: 400, request id: **3d3736d6-77b0-4a03-9139-857a366cad7a**

[npk errors.txt](https://github.com/Coalfire-Research/npk/files/4498266/npk.errors.txt)

**Comment by hashtaginfosec** [comment]
Looks like your deployment is hosed and you're trying to deploy against an environment that already has some artifats. If you search issues on this repo, you'll find errors similar to yours were fixed by performing a terraform destroy. It's also quite possible you'll need to manually delete any stubborn artifacts.

**Comment by glwallum** [comment]
Thanks, I tried terraform destroy but that errored out as well.

New AWS account and good to go
