### ISSUE TITLE
Starting campaign - Error requesting spot fleet

### ISSUE THREAD

**Issue by glwallum** [Coalfire-Research/npk#89]
Hi

I have a successful deployment of NPK. When trying start a campaign, I receive the error below. 

Error: Error requesting spot fleet: AuthFailure.ServiceLinkedRoleCreationNotPermitted: The provided credentials do not have permission to create the service-linked role for EC2 Spot Fleet.

**Comment by awhitehatter** [comment]
@glwallum thanks for posting, are you still having this issue? Seems like the either the role created by NPK doesn't exist, or you don't have the permissions to assume the role.
