### ISSUE TITLE
Settings Button not displaying menu

### ISSUE THREAD

**Issue by derhornspieler** [Coalfire-Research/npk#91]
<img width="1216" alt="Screen Shot 2020-04-29 at 12 00 49 AM" src="https://user-images.githubusercontent.com/15236687/80562224-b6a70200-89ac-11ea-8094-4a07183d7e8b.png">

**Comment by awhitehatter** [comment]
Thanks for posting @derhornspieler . Unfortunately, this is a known issues, a setting page has not been implemented yet. I'm working on it.

**Comment by awhitehatter** [comment]
known issue, will fix in next release.
