### ISSUE TITLE
CRC32 error

### ISSUE THREAD

**Issue by averonesis** [Coalfire-Research/npk#92]
Hello, 
After a new campaign has been created I got this in next 10-15 min 
npkMainCtrl.js:444 Uncaught (in promise) Error: CRC32CheckFailed: CRC32 integrity check failed
    at npkMainCtrl.js:444
If I cleared some dynamoDB files via aws console - this error disappear again for some time

**Comment by sw33tr0ll** [comment]
Hi, I did some research on this last night and think I should have a fix (or at least a good workaround) ready this weekend. More to come

**Comment by awhitehatter** [comment]
@averonesis thanks for posting, when this occurs again, would you mind copy/pasting from your browser console?

**Comment by awhitehatter** [comment]
Closing no response.
