### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by jbertman** [Coalfire-Research/npk#93]
Firstly, thank you for all of your hard work on NPK. It has been extremely helpful on engagements. I decided that I would update our instance today, and that has lead to the following problem:

From a fresh clone on the latest master, I can modify npk-settings.json and successfully deploy using terraform v0.11. After logging in with the newly created user, I noticed that all of the preflight requests for public dictionaries are failing with `No 'Access-Control-Allow-Origin' header is present on the requested resource.`

The current NPK dictionary I am receiving in my configuration is pointing at the following URL:
https://npk-dictionary-west-2-20181029005812750900000002-2.s3.us-west-2.amazonaws.com/?max-keys=100&prefix=wordlist%2F

I can successfully reach the bucket directly from the browser, but there seems to a CORS misconfiguration on it. Are these the correct public links? Or is there a current CORS issue that I'm missing?

Would it be easier to just selfhost the configuration?

Thanks in advance!

**Comment by awhitehatter** [comment]
We had to update our community buckets, thanks for the heads up here, missed one of the CORS configs. Will update soon.

**Comment by jbertman** [comment]
Sounds good - thanks for the quick response! Feel free to close when ready.

**Comment by thalesredteam** [comment]
> Sounds good - thanks for the quick response! Feel free to close when ready.

Did you figure out any way around this issue jbert?
