### ISSUE TITLE
JWT Hashtype Bug

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#94]
Hello, 

NPK shows ???/$ for instance cost if you select JWT as hash type. Any reason why this is seems to only happen with JWT hash type?

Thanks,

**Comment by bzekanovic** [comment]
Also, looks like job just errors out even when using example JWT hash from Hashcat site https://hashcat.net/wiki/doku.php?id=example_hashes

**Comment by awhitehatter** [comment]
Interesting. I'll dig into this soon. Thanks for posting.

**Comment by bzekanovic** [comment]
@awhitehatter  

Following up to see if you were able to replicate this on your side?

**Comment by c6fc** [comment]
The display is fixed in v2. This was likely due to it not being present in the 5.0.0 benchmarks, which is what the campaign instance cards pull from

As for it erroring out with JWT campaigns, I'll give that a shot tomorrow and see if I can replicate.

**Comment by bzekanovic** [comment]
Looks good thx!
