### ISSUE TITLE
Lambda functions won't create during run of deploy.sh due to unsupported nodeJS runtime 6.10

### ISSUE THREAD

**Issue by JesYo** [Coalfire-Research/npk#95]
Hello!

First off -- love this project! Admittedly I haven't used my NPK deployment for about a year or so, but I have a few hard-to-crack hashes that I'd like to get through at the moment. I decided to terraform destroy and rebuild my deployment in AWS, after which I noticed that trying to run ./deploy.sh resulted in errors while attempting to create each of the three lambda functions. Looks like the nodejs6.10 runtime is no longer supported for aws lambda functions. I tried manually changing the nodejs version strings inside npk/terraform/lambda_functions.tf.json, but it looks like they get overwritten during execution of ./deploy.sh? Wanted to see if this was a known issue or just something specific that I messed up on. Thanks!

![image](https://user-images.githubusercontent.com/20176751/82501050-cf896b80-9ab1-11ea-9004-a69241308a0b.png)

**Comment by bzekanovic** [comment]
You should pull down new version of master branch since they updated node version https://github.com/Coalfire-Research/npk/blob/master/terraform/jsonnet/lambda_functions.libsonnet

**Comment by awhitehatter** [comment]
@JesYo glad you love the project, we're working on improving it! As @bzekanovic  mentioned, pull the latest branch and see. Thx!
