### ISSUE TITLE
Authentication Failed 

### ISSUE THREAD

**Issue by marti2221** [Coalfire-Research/npk#96]
From what I can tell, I've successfully deployed npk. The output values appear to be as expected. However when i move to the cloudfront url and try to log in with the user and pass given in my outputs, I'm getting an authentication failed error. I copy pasted the user and pass right from the terminal so I'm not sure why this would be happening.

**Comment by marti2221** [comment]
im also receiving no invitation email like i had in the past.

**Comment by dak-csis** [comment]
Hi, I am having the same issue.
I've been running deploy.sh a few (many times) with errors, slowly resolving them one by one. Finally I reached the last green line, and I can access the CloudFront site but my user/pass does not work, password reset does not work, and I do not get the confirmation email.

**Comment by awhitehatter** [comment]
Apologies for the delayed response, we field issues when we can. Is this still going on for both of you? If you log into your account, do you see the pool with your user in the Cognito service?

**Comment by dak-csis** [comment]
Hi,
I see no users in the Cognito service for NPK.

**Comment by dak-csis** [comment]
If there is any debugging steps you believe could help, I'll be happy to perform them. I'm very comfortable in code and console, but have 0 experience with AWS tech outside of ec2 so far.

After manually adding a user for NPK in Cognito, I successfully logged in.

**Comment by c6fc** [comment]
This is likely a problem with the local provisioner responsible for creating the cognito user. If you run `terraform show` after a succesful installation, you'll see an output called 'admin_create_user_command'. If you copy/paste that into the terminal, it'll create the user and send the email.

... or show you the error that caused it to fail the first time.
