### ISSUE TITLE
Hashcat 6.0

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#99]
New version of Hashcat is out https://hashcat.net/forum/thread-9303.html.

**Comment by bzekanovic** [comment]
Also, what is the process to update Hashcat version with current deployment?

**Comment by icryo** [comment]
https://github.com/Coalfire-Research/npk/blob/a9809d0161f1ae7f341fa411ebccb885df64b0e4/terraform-selfhost/npk-selfhost.auto.tfvars.sample

I plan to adjust this and test for stability shortly.

**Comment by awhitehatter** [comment]
Thanks, I set up a dev branch to run changes through. Testing this today/tomorrow.

**Comment by icryo** [comment]
Worked fine on my end. 👍

**Comment by c6fc** [comment]
I'll test this as a part of v2, and if it works OK, I'll get the new benchmarks and hashtypes collected for it.

**Comment by c6fc** [comment]
I was able to get it working with some moderate tweaks. I'm gathering benchmarks and hope to have the changes pushed before the weekend.

**Comment by c6fc** [comment]
NPK now uses Hashcat 6.1.1 as of v2 784ca91

**Comment by c6fc** [comment]
Note to folks who are super excited about this: I'm not able to upload the 6.1.1 components to the prod buckets until Coalfire remedies some access limitations. Worst-case, we're looking at tomorrow before the community buckets will be usable on V2 HEAD. Self-hosted is slightly impacted as well, but should work for v2.
